// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_tajimas_d
double rcpp_tajimas_d(Rcpp::IntegerMatrix mat);
RcppExport SEXP _genomicpp_rcpp_tajimas_d(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_tajimas_d(mat));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_tajimas_d
Rcpp::NumericVector rcpp_parallel_tajimas_d(Rcpp::IntegerMatrix mat);
RcppExport SEXP _genomicpp_rcpp_parallel_tajimas_d(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_tajimas_d(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genomicpp_rcpp_tajimas_d", (DL_FUNC) &_genomicpp_rcpp_tajimas_d, 1},
    {"_genomicpp_rcpp_parallel_tajimas_d", (DL_FUNC) &_genomicpp_rcpp_parallel_tajimas_d, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_genomicpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
