# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' rcpp_tajimas_d
#'
#' @name rcpp_tajimas_d
#' @param mat The input matrix (k markers times n individuals).
#' @return rmat The output matrix (n individuals times n)
#'
#' @export
rcpp_tajimas_d <- function(mat) {
    .Call(`_genomicpp_rcpp_tajimas_d`, mat)
}

#'
#' rcpp_parallel_tajimas_d
#'
#' @name rcpp_parallel_tajimas_d
#' @param mat The input matrix (k markers times n individuals).
#' @return rmat The output vector
#'
#' @export
rcpp_parallel_tajimas_d <- function(mat) {
    .Call(`_genomicpp_rcpp_parallel_tajimas_d`, mat)
}

